email 인증 기능 설정 추가
team-devOops/Chal-Chal-Server pull request #4
Opened 2022-09-29 08:29 UTC by zinzoddari

2022-09-29 14:57 UTC, benggrae requested changes

2022-09-29 14:57 UTC, benggrae commented on src/main/java/com/chalchal/chalchalsever/auth/service/UserService.java
>      User findByEmailAndPassword(String email, String password);
엔티티 클래스를 Controller 레이어까지 사용되고 있는거 같아요.

관련글 참조 해보시고 생각해보세여 
https://xlffm3.github.io/spring%20&%20spring%20boot/DTOLayer/

2022-09-29 14:57 UTC, benggrae commented on src/main/java/com/chalchal/chalchalsever/dto/TokenResponse.java
> -    private String REFRESH_TOKEN;
카멜케이스 변환 👍

2022-09-29 14:57 UTC, benggrae commented on src/main/java/com/chalchal/chalchalsever/auth/controller/AuthController.java
> +        if(userService.validateRegister(userRequest.getEmail())) {
컨트롤러에 비지니스 정책이 "이메일을 있는지 체크"의 내용이 담겨있는듯 한데 
컨트롤러에서는 웹계층의 내용만 담겨 있어야 한다고 생각하는데 어떻게 생각하시나요?

개인적으로 하나의 서비스 메세드에서 "이메일을 있는지 체크", "등록" 을 수행하고 ResponseEntity반환을 위임하는건 어떨까요?

2022-09-29 14:57 UTC, benggrae commented on src/main/java/com/chalchal/chalchalsever/auth/controller/AuthController.java
> +        long refreshTokenIndex = jwtUtils.getRefreshTokenByCookieIndex(httpServletRequest, REFRESH_TOKEN_INDEX);
클래스명 의미에 맞게 리팩토링 👍

2022-09-29 14:57 UTC, benggrae commented on src/main/java/com/chalchal/chalchalsever/auth/controller/AuthController.java
> +        return null;
개발중인거겠죠?

2022-09-29 15:46 UTC, benggrae commented
전체적으로 ResponseEntity<?> 로 컨트롤러에서 반환하는데 구체적인 DTO를 반환하는게 좋을것 같아요 
고민해보시지요

2022-09-30 00:21 UTC, zinzoddari commented on src/main/java/com/chalchal/chalchalsever/auth/service/UserService.java
>      User findByEmailAndPassword(String email, String password);
넵 참고해서 수정했습니다 : ) 이후에도 고려해서 개발하도록 하겠습니다

2022-09-30 00:22 UTC, zinzoddari commented on src/main/java/com/chalchal/chalchalsever/dto/TokenResponse.java
> -    private String REFRESH_TOKEN;
감사 ~.^ 합니다

2022-09-30 00:22 UTC, zinzoddari commented on src/main/java/com/chalchal/chalchalsever/auth/controller/AuthController.java
> +        if(userService.validateRegister(userRequest.getEmail())) {
넵 따로 서비스를 만들 예정입니다

2022-09-30 00:22 UTC, zinzoddari commented on src/main/java/com/chalchal/chalchalsever/auth/controller/AuthController.java
> +        long refreshTokenIndex = jwtUtils.getRefreshTokenByCookieIndex(httpServletRequest, REFRESH_TOKEN_INDEX);
감사 ~.^ 합니다

2022-09-30 00:22 UTC, zinzoddari commented on src/main/java/com/chalchal/chalchalsever/auth/controller/AuthController.java
> +        return null;
넹 ㅎ;

2022-10-03 10:40 UTC, merged